/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    categories: Category;
    'government-sources': GovernmentSource;
    articles: Article;
    faqs: Faq;
    'newsletter-subscribers': NewsletterSubscriber;
    resources: Resource;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'government-sources': GovernmentSourcesSelect<false> | GovernmentSourcesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'ar' | 'ur' | 'hi' | 'bn' | 'tl')
    | ('en' | 'ar' | 'ur' | 'hi' | 'bn' | 'tl')[];
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
    'seo-pages': SeoPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'seo-pages': SeoPagesSelect<false> | SeoPagesSelect<true>;
  };
  locale: 'en' | 'ar' | 'ur' | 'hi' | 'bn' | 'tl';
  widgets: {
    overview: OverviewWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  roles: ('super-admin' | 'admin' | 'editor')[];
  preferredLocale?: ('en' | 'ar' | 'ur' | 'hi' | 'bn' | 'tl') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  fullName: string;
  /**
   * Automatically generated from the title or name. Edit only if necessary.
   */
  slug: string;
  photo?: (number | null) | Media;
  jobTitle?: string | null;
  shortBio?: string | null;
  status: 'active' | 'inactive';
  verifiedAuthor?: boolean | null;
  credentials?:
    | {
        title: string;
        organization?: string | null;
        id?: string | null;
      }[]
    | null;
  linkedin?: string | null;
  website?: string | null;
  createdBy?: (number | null) | User;
  lastModifiedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Automatically generated from the title or name. Edit only if necessary.
   */
  slug: string;
  description?: string | null;
  icon?: (number | null) | Media;
  status: 'active' | 'inactive' | 'archived';
  sortOrder?: number | null;
  createdBy?: (number | null) | User;
  lastModifiedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "government-sources".
 */
export interface GovernmentSource {
  id: number;
  name: string;
  /**
   * Official government website (e.g. https://hrsd.gov.sa)
   */
  officialWebsite: string;
  logo?: (number | null) | Media;
  status: 'active' | 'inactive';
  createdBy?: (number | null) | User;
  lastModifiedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Automatically generated from the title or name. Edit only if necessary.
   */
  slug: string;
  subtitle?: string | null;
  excerpt?: string | null;
  /**
   * Supports multilingual rich content.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage: number | Media;
  category: number | Category;
  author: number | Author;
  relatedArticles?: (number | Article)[] | null;
  governmentSources?: (number | GovernmentSource)[] | null;
  /**
   * Optional. Falls back to the article title.
   */
  metaTitle?: string | null;
  /**
   * Optional. Falls back to the article excerpt.
   */
  metaDescription?: string | null;
  /**
   * Optional. Falls back to the featured image.
   */
  ogImage?: (number | null) | Media;
  /**
   * Discourage search engines from indexing this page.
   */
  noIndex?: boolean | null;
  /**
   * Discourage search engines from following links on this page.
   */
  noFollow?: boolean | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * Automatically updated whenever the content is fact checked.
   */
  lastVerifiedAt?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  verifiedBy?: (number | null) | User;
  factChecked?: boolean | null;
  sourceLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  readingTime?: number | null;
  viewCount?: number | null;
  createdBy?: (number | null) | User;
  lastModifiedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: (number | null) | Category;
  relatedArticles?: (number | Article)[] | null;
  sortOrder?: number | null;
  createdBy?: (number | null) | User;
  lastModifiedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  locale: 'en' | 'ar' | 'ur' | 'hi' | 'bn' | 'tl';
  source?: ('website' | 'article' | 'landing-page' | 'popup') | null;
  status: 'subscribed' | 'unsubscribed' | 'bounced';
  subscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  description?: string | null;
  icon?: (number | null) | Media;
  category: 'government-services' | 'useful-apps' | 'emergency-numbers' | 'public-services';
  url: string;
  sortOrder?: number | null;
  status: 'active' | 'inactive';
  createdBy?: (number | null) | User;
  lastModifiedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'government-sources';
        value: number | GovernmentSource;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  roles?: T;
  preferredLocale?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  photo?: T;
  jobTitle?: T;
  shortBio?: T;
  status?: T;
  verifiedAuthor?: T;
  credentials?:
    | T
    | {
        title?: T;
        organization?: T;
        id?: T;
      };
  linkedin?: T;
  website?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  status?: T;
  sortOrder?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "government-sources_select".
 */
export interface GovernmentSourcesSelect<T extends boolean = true> {
  name?: T;
  officialWebsite?: T;
  logo?: T;
  status?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  author?: T;
  relatedArticles?: T;
  governmentSources?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noIndex?: T;
  noFollow?: T;
  status?: T;
  publishedAt?: T;
  lastVerifiedAt?: T;
  featured?: T;
  sortOrder?: T;
  verifiedBy?: T;
  factChecked?: T;
  sourceLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  readingTime?: T;
  viewCount?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  relatedArticles?: T;
  sortOrder?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  locale?: T;
  source?: T;
  status?: T;
  subscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  category?: T;
  url?: T;
  sortOrder?: T;
  status?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  identity: {
    siteName: string;
    organizationName: string;
    tagline?: string | null;
    shortDescription?: string | null;
  };
  logos?: {
    primaryLogo?: (number | null) | Media;
    whiteLogo?: (number | null) | Media;
    darkLogo?: (number | null) | Media;
    favicon?: (number | null) | Media;
    appleTouchIcon?: (number | null) | Media;
  };
  /**
   * Colors used when the website is in light mode.
   */
  light: {
    /**
     * Choose a color or enter a HEX value.
     */
    primary: string;
    /**
     * Choose a color or enter a HEX value.
     */
    primaryForeground: string;
    /**
     * Choose a color or enter a HEX value.
     */
    secondary: string;
    /**
     * Choose a color or enter a HEX value.
     */
    secondaryForeground: string;
    /**
     * Choose a color or enter a HEX value.
     */
    accent: string;
    /**
     * Choose a color or enter a HEX value.
     */
    accentForeground: string;
    /**
     * Choose a color or enter a HEX value.
     */
    background: string;
    /**
     * Choose a color or enter a HEX value.
     */
    foreground: string;
    /**
     * Choose a color or enter a HEX value.
     */
    card: string;
    /**
     * Choose a color or enter a HEX value.
     */
    cardForeground: string;
    /**
     * Choose a color or enter a HEX value.
     */
    muted: string;
    /**
     * Choose a color or enter a HEX value.
     */
    mutedForeground: string;
  };
  /**
   * Colors used when the website is in dark mode.
   */
  dark: {
    /**
     * Choose a color or enter a HEX value.
     */
    primary: string;
    /**
     * Choose a color or enter a HEX value.
     */
    primaryForeground: string;
    /**
     * Choose a color or enter a HEX value.
     */
    secondary: string;
    /**
     * Choose a color or enter a HEX value.
     */
    secondaryForeground: string;
    /**
     * Choose a color or enter a HEX value.
     */
    accent: string;
    /**
     * Choose a color or enter a HEX value.
     */
    accentForeground: string;
    /**
     * Choose a color or enter a HEX value.
     */
    background: string;
    /**
     * Choose a color or enter a HEX value.
     */
    foreground: string;
    /**
     * Choose a color or enter a HEX value.
     */
    card: string;
    /**
     * Choose a color or enter a HEX value.
     */
    cardForeground: string;
    /**
     * Choose a color or enter a HEX value.
     */
    muted: string;
    /**
     * Choose a color or enter a HEX value.
     */
    mutedForeground: string;
  };
  site: {
    /**
     * The canonical base URL of your website.
     */
    siteUrl: string;
    defaultMetaTitle: string;
    defaultMetaDescription?: string | null;
  };
  verification?: {
    /**
     * Paste the Google Search Console verification token.
     */
    googleVerification?: string | null;
    /**
     * Paste the Bing Webmaster verification token.
     */
    bingVerification?: string | null;
  };
  structuredData: {
    organizationType: 'Organization' | 'Corporation' | 'NewsMediaOrganization' | 'EducationalOrganization';
  };
  socialProfiles?: {
    /**
     * Enter a valid URL.
     */
    facebook?: string | null;
    /**
     * Enter a valid URL.
     */
    instagram?: string | null;
    /**
     * Enter a valid URL.
     */
    x?: string | null;
    /**
     * Enter a valid URL.
     */
    linkedin?: string | null;
    /**
     * Enter a valid URL.
     */
    youtube?: string | null;
    /**
     * Enter a valid URL.
     */
    tiktok?: string | null;
    /**
     * Enter a valid URL.
     */
    telegram?: string | null;
  };
  services?: {
    /**
     * Example: G-XXXXXXXXXX
     */
    googleAnalyticsId?: string | null;
    /**
     * Example: GTM-XXXXXXX
     */
    googleTagManagerId?: string | null;
    microsoftClarityId?: string | null;
    /**
     * Example: ca-pub-1234567890123456
     */
    googleAdsenseId?: string | null;
  };
  website?: {
    maintenanceMode?: boolean | null;
    enableSearch?: boolean | null;
    enableDarkMode?: boolean | null;
  };
  content?: {
    enableReadingTime?: boolean | null;
    enableTableOfContents?: boolean | null;
    enableRelatedArticles?: boolean | null;
  };
  ads?: {
    enableAds?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  categoryFilters?: (number | Category)[] | null;
  popularSearches?:
    | {
        title: string;
        query: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-pages".
 */
export interface SeoPage {
  id: number;
  home?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
  };
  articles?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
  };
  categories?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
  };
  authors?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
  };
  about?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
  };
  contact?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
  };
  privacy?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
  };
  terms?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
  };
  search?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
  };
  error404?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  identity?:
    | T
    | {
        siteName?: T;
        organizationName?: T;
        tagline?: T;
        shortDescription?: T;
      };
  logos?:
    | T
    | {
        primaryLogo?: T;
        whiteLogo?: T;
        darkLogo?: T;
        favicon?: T;
        appleTouchIcon?: T;
      };
  light?:
    | T
    | {
        primary?: T;
        primaryForeground?: T;
        secondary?: T;
        secondaryForeground?: T;
        accent?: T;
        accentForeground?: T;
        background?: T;
        foreground?: T;
        card?: T;
        cardForeground?: T;
        muted?: T;
        mutedForeground?: T;
      };
  dark?:
    | T
    | {
        primary?: T;
        primaryForeground?: T;
        secondary?: T;
        secondaryForeground?: T;
        accent?: T;
        accentForeground?: T;
        background?: T;
        foreground?: T;
        card?: T;
        cardForeground?: T;
        muted?: T;
        mutedForeground?: T;
      };
  site?:
    | T
    | {
        siteUrl?: T;
        defaultMetaTitle?: T;
        defaultMetaDescription?: T;
      };
  verification?:
    | T
    | {
        googleVerification?: T;
        bingVerification?: T;
      };
  structuredData?:
    | T
    | {
        organizationType?: T;
      };
  socialProfiles?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        x?: T;
        linkedin?: T;
        youtube?: T;
        tiktok?: T;
        telegram?: T;
      };
  services?:
    | T
    | {
        googleAnalyticsId?: T;
        googleTagManagerId?: T;
        microsoftClarityId?: T;
        googleAdsenseId?: T;
      };
  website?:
    | T
    | {
        maintenanceMode?: T;
        enableSearch?: T;
        enableDarkMode?: T;
      };
  content?:
    | T
    | {
        enableReadingTime?: T;
        enableTableOfContents?: T;
        enableRelatedArticles?: T;
      };
  ads?:
    | T
    | {
        enableAds?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  categoryFilters?: T;
  popularSearches?:
    | T
    | {
        title?: T;
        query?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-pages_select".
 */
export interface SeoPagesSelect<T extends boolean = true> {
  home?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        noFollow?: T;
      };
  articles?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        noFollow?: T;
      };
  categories?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        noFollow?: T;
      };
  authors?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        noFollow?: T;
      };
  about?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        noFollow?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        noFollow?: T;
      };
  privacy?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        noFollow?: T;
      };
  terms?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        noFollow?: T;
      };
  search?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        noFollow?: T;
      };
  error404?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "overview_widget".
 */
export interface OverviewWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}